# -*- coding: utf-8 -*-
"""PlantdiseaseDetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1gskkY27jUz5FIKUVERTrLV2hnXSuSF
"""

# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8pkxTlaLxoFV7MJFWxYdkiphkK59oRP
"""

import os
import sys
import json
import shutil
import random
import subprocess
import datetime
import time
import hashlib


# SECTION 1 — INSTALL ONLY WHAT'S MISSING (fast; does not touch TensorFlow)


print("SECTION 1 - Installing missing dependencies (TensorFlow is left as-is)")

EXTRA_PACKAGES = [
    "opencv-python-headless",
    "flask==3.0.3",
    "pyngrok==7.2.0",
]
subprocess.run([sys.executable, "-m", "pip", "install", "-q"] + EXTRA_PACKAGES, check=False)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input as efficientnet_preprocess
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models, optimizers, callbacks, losses

from sklearn.metrics import (classification_report, confusion_matrix, f1_score,
                              precision_score, recall_score, accuracy_score, roc_auc_score)

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print("TensorFlow:", tf.__version__)
gpus = tf.config.list_physical_devices("GPU")
print("GPU available:", gpus)
if not gpus:
    print("\n*** WARNING: no GPU detected. Training will be very slow on CPU. ***")
    print("*** Go to Runtime -> Change runtime type -> GPU (T4), restart, and re-run. ***\n")



# SPEED / ACCURACY CONTROLS

FAST_MODE = True        # True = quick smoke-test run. Set False for a real accuracy run.
SAMPLE_FRAC = 0.25       # Fraction of your manifest to use (1.0 = all of it - recommended for real results).
BATCH_SIZE = 64 if gpus else 32

# Stage 1: frozen EfficientNet base, train only the new classification head.
EPOCHS_STAGE1 = 6 if FAST_MODE else 20
# Stage 2: unfreeze most of EfficientNet and fine-tune end-to-end at a low LR.
EPOCHS_STAGE2 = 4 if FAST_MODE else 15
UNFREEZE_LAST_N_LAYERS = 100

print(f"FAST_MODE={FAST_MODE}  SAMPLE_FRAC={SAMPLE_FRAC}  BATCH_SIZE={BATCH_SIZE}  "
      f"EPOCHS_STAGE1={EPOCHS_STAGE1}  EPOCHS_STAGE2={EPOCHS_STAGE2}")
print("For a genuine accuracy run: FAST_MODE=False and SAMPLE_FRAC=1.0 (real photos are now downloaded automatically below).")



# SECTION 2 — DATA: RAW MANIFEST -> CLEANED MANIFEST


print("SECTION 2 - Upload plantvillage_cleaned_balanced.csv")

manifest_path = None
try:
    from google.colab import files
    print("Please choose plantvillage_cleaned_balanced.csv")
    uploaded = files.upload()
    manifest_path = [f for f in uploaded.keys() if f.lower().endswith(".csv")][0]
except ImportError:
    manifest_path = input("Enter the path to plantvillage_cleaned_balanced.csv: ").strip()

raw_df = pd.read_csv(manifest_path)
print(f"Raw manifest loaded: {len(raw_df)} rows, columns: {list(raw_df.columns)}")

quality_flags = ["is_corrupted", "is_duplicate", "has_wrong_label", "is_low_resolution"]
present_flags = [c for c in quality_flags if c in raw_df.columns]

before = len(raw_df)
mask_clean = np.ones(len(raw_df), dtype=bool)
for flag in present_flags:
    removed_by_flag = int(raw_df[flag].sum())
    print(f"  {flag}: {removed_by_flag} rows flagged True (will be removed)")
    mask_clean &= ~raw_df[flag].astype(bool)

cleaned_df = raw_df[mask_clean].reset_index(drop=True)
after = len(cleaned_df)
print(f"\nRaw rows: {before}  ->  Cleaned rows: {after}  (removed {before - after})")

cleaned_df = cleaned_df.dropna(subset=["image_id", "disease_class", "split"]).reset_index(drop=True)

if SAMPLE_FRAC < 1.0:
    cleaned_df = (
        cleaned_df.groupby(["disease_class", "split"], group_keys=False)
        .sample(frac=SAMPLE_FRAC, random_state=SEED)
        .reset_index(drop=True)
    )
    print(f"SAMPLE_FRAC={SAMPLE_FRAC} applied -> using {len(cleaned_df)} rows this run.")

CLASS_NAMES = sorted(cleaned_df["disease_class"].unique().tolist())
NUM_CLASSES = len(CLASS_NAMES)
print(f"\n{NUM_CLASSES} disease classes detected across {cleaned_df['crop'].nunique()} crops.")
print("\nSplit sizes used this run:")
print(cleaned_df["split"].value_counts())


# SECTION 2.05 — DOWNLOAD REAL PLANTVILLAGE PHOTOS


print("SECTION 2.05 - Downloading real PlantVillage photos from Kaggle")


subprocess.run([sys.executable, "-m", "pip", "install", "-q", "kaggle"], check=False)

KAGGLE_DATASET_SLUG = "abdallahalidev/plantvillage-dataset"  # full 14-crop/38-class set, matches your manifest
REAL_DOWNLOAD_ROOT = "/content/kaggle_real_images" if os.path.isdir("/content") else "./kaggle_real_images"

kaggle_ready = os.path.exists(os.path.expanduser("~/.kaggle/kaggle.json"))
if not kaggle_ready:
    try:
        from google.colab import files
        print("Upload your kaggle.json (from https://www.kaggle.com/settings -> API -> Create New Token).")
        print("This lets the notebook download real leaf photos instead of colour-block placeholders.")
        uploaded = files.upload()
        json_name = next((f for f in uploaded if f.lower().endswith(".json")), None)
        if json_name:
            os.makedirs(os.path.expanduser("~/.kaggle"), exist_ok=True)
            shutil.copy(json_name, os.path.expanduser("~/.kaggle/kaggle.json"))
            os.chmod(os.path.expanduser("~/.kaggle/kaggle.json"), 0o600)
            kaggle_ready = True
    except ImportError:
        print("Not running in Colab - place kaggle.json at ~/.kaggle/kaggle.json yourself, then re-run.")

if kaggle_ready and not os.path.isdir(REAL_DOWNLOAD_ROOT):
    os.makedirs(REAL_DOWNLOAD_ROOT, exist_ok=True)
    result = subprocess.run(
        ["kaggle", "datasets", "download", "-d", KAGGLE_DATASET_SLUG,
         "-p", REAL_DOWNLOAD_ROOT, "--unzip"],
        capture_output=True, text=True)
    print(result.stdout[-1500:])
    if result.returncode != 0:
        print(result.stderr[-1500:])
        print("\nDownload failed - visit https://www.kaggle.com/datasets/" + KAGGLE_DATASET_SLUG,
              "and click 'Download' once on the website to accept its terms, then re-run this cell.")


def build_real_images_by_class(search_root, class_names):
    """Recursively scan the downloaded dataset and, for every folder whose name
    exactly matches one of this project's disease_class names, collect every
    image file inside it. Real datasets ship several near-duplicate folder
    trees (color/grayscale/segmented) - all matching folders are pooled."""
    by_class = {c: [] for c in class_names}
    if not (search_root and os.path.isdir(search_root)):
        return by_class
    class_set = set(class_names)
    for dirpath, dirnames, filenames in os.walk(search_root):
        folder_name = os.path.basename(dirpath)
        if folder_name in class_set:
            imgs = [os.path.join(dirpath, f) for f in filenames
                    if f.lower().endswith((".jpg", ".jpeg", ".png"))]
            by_class[folder_name].extend(imgs)
    return by_class


REAL_IMAGES_BY_CLASS = build_real_images_by_class(REAL_DOWNLOAD_ROOT, CLASS_NAMES)
classes_with_real_photos = sum(1 for c in CLASS_NAMES if REAL_IMAGES_BY_CLASS[c])
total_real_photos = sum(len(v) for v in REAL_IMAGES_BY_CLASS.values())
print(f"\nFound real photos for {classes_with_real_photos}/{NUM_CLASSES} classes "
      f"({total_real_photos} images total).")
missing_classes = [c for c in CLASS_NAMES if not REAL_IMAGES_BY_CLASS[c]]
if missing_classes:
    print("Classes with NO real photos found (will fall back to a placeholder for these only):")
    for c in missing_classes:
        print("  -", c)


# SECTION 2.1 — MATERIALISE IMAGES


print("SECTION 2.1 - Materialising images (real photos, cycled per class)")


IMAGE_ROOT = "/content/pv_images" if os.path.isdir("/content") else "./pv_images"
TEMPLATE_ROOT = "/content/pv_class_templates" if os.path.isdir("/content") else "./pv_class_templates"
os.makedirs(IMAGE_ROOT, exist_ok=True)
os.makedirs(TEMPLATE_ROOT, exist_ok=True)

import itertools
real_image_cyclers = {
    c: itertools.cycle(REAL_IMAGES_BY_CLASS[c]) for c in CLASS_NAMES if REAL_IMAGES_BY_CLASS[c]
}


def make_class_template_bgr(disease_class, size=224):
    """Fallback only - used exclusively for a class with zero real photos found.
    Uses hashlib (not Python's built-in hash()) so the seed - and therefore the
    image - is identical every run and every machine."""
    seed = int(hashlib.md5(disease_class.encode()).hexdigest(), 16) % (2 ** 32 - 1)
    rng = np.random.default_rng(seed)
    base_color = rng.integers(30, 220, size=3)
    noise = rng.integers(-25, 25, size=(size, size, 3))
    arr_rgb = np.clip(base_color + noise, 0, 255).astype(np.uint8)
    return cv2.cvtColor(arr_rgb, cv2.COLOR_RGB2BGR)


template_paths = {}
for cls in CLASS_NAMES:
    tpath = os.path.join(TEMPLATE_ROOT, f"{cls}.jpg")
    if not os.path.exists(tpath):
        cv2.imwrite(tpath, make_class_template_bgr(cls))
    template_paths[cls] = tpath

filepaths = []
real_found = 0
for row in cleaned_df.itertuples(index=False):
    dest_path = os.path.join(IMAGE_ROOT, row.image_id)
    if not os.path.exists(dest_path):
        cycler = real_image_cyclers.get(row.disease_class)
        if cycler is not None:
            shutil.copy(next(cycler), dest_path)
            real_found += 1
        else:
            try:
                os.link(template_paths[row.disease_class], dest_path)
            except OSError:
                shutil.copy(template_paths[row.disease_class], dest_path)
    filepaths.append(dest_path)

cleaned_df["filepath"] = filepaths
print(f"Materialised {len(cleaned_df)} images at {IMAGE_ROOT}")
print(f"  -> {real_found} are real PlantVillage photos")
print(f"  -> {len(cleaned_df) - real_found} fell back to a placeholder template (class had no real photos)")
if real_found == 0:
    print("\n  *** STILL on placeholder images for everything - the Kaggle download above must have")
    print("  *** failed. Scroll up to its error message, fix it, then re-run from Section 2.05. ***")
elif real_found < len(cleaned_df):
    print(f"\n  Note: {len(cleaned_df) - real_found} row(s) still used placeholders (classes listed above).")


# SECTION 3 — AUGMENTATION & GENERATORS (bug fix is here)


print("SECTION 3 - Augmentation & data generators (EfficientNet-correct preprocessing)")


IMG_SIZE = (224, 224)

train_df = cleaned_df[cleaned_df["split"] == "train"].reset_index(drop=True)
val_df = cleaned_df[cleaned_df["split"].isin(["val", "validation"])].reset_index(drop=True)
test_df = cleaned_df[cleaned_df["split"] == "test"].reset_index(drop=True)
print(f"train={len(train_df)}  val={len(val_df)}  test={len(test_df)}")

train_datagen = ImageDataGenerator(
    preprocessing_function=efficientnet_preprocess,
    rotation_range=30,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.2,
    brightness_range=[0.8, 1.2],
    horizontal_flip=True,
    vertical_flip=True,
    fill_mode="nearest",
)
eval_datagen = ImageDataGenerator(preprocessing_function=efficientnet_preprocess)


def make_generators():
    train_gen = train_datagen.flow_from_dataframe(
        train_df, x_col="filepath", y_col="disease_class", target_size=IMG_SIZE,
        batch_size=BATCH_SIZE, class_mode="categorical", classes=CLASS_NAMES,
        shuffle=True, seed=SEED)
    val_gen = eval_datagen.flow_from_dataframe(
        val_df, x_col="filepath", y_col="disease_class", target_size=IMG_SIZE,
        batch_size=BATCH_SIZE, class_mode="categorical", classes=CLASS_NAMES, shuffle=False)
    test_gen = eval_datagen.flow_from_dataframe(
        test_df, x_col="filepath", y_col="disease_class", target_size=IMG_SIZE,
        batch_size=BATCH_SIZE, class_mode="categorical", classes=CLASS_NAMES, shuffle=False)
    return train_gen, val_gen, test_gen


train_gen, val_gen, test_gen = make_generators()


sample_batch, _ = next(train_gen)
fig, axes = plt.subplots(1, 6, figsize=(18, 3))
for i, ax in enumerate(axes):
    disp = sample_batch[i] - sample_batch[i].min()
    disp = disp / (disp.max() + 1e-8)
    ax.imshow(disp)
    ax.axis("off")
fig.suptitle("Sample augmented training images (renormalised for display only)")
plt.show()
train_gen.reset()



# SECTION 4 — MODEL: EfficientNetB0 TRANSFER LEARNING


print("SECTION 4 - Training EfficientNetB0")



def build_model(num_classes):
    base_model = EfficientNetB0(include_top=False, weights="imagenet", input_shape=(224, 224, 3))
    base_model.trainable = False
    inputs = layers.Input(shape=(224, 224, 3))
    x = base_model(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(256, activation="relu")(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)
    return models.Model(inputs, outputs, name="EfficientNetB0"), base_model


model, base_model = build_model(NUM_CLASSES)
loss_fn = losses.CategoricalCrossentropy(label_smoothing=0.1)

model.compile(optimizer=optimizers.Adam(learning_rate=1e-3), loss=loss_fn, metrics=["accuracy"])

es = callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
rlrop = callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-7)
ckpt_path = "/content/EfficientNetB0_best.keras" if os.path.isdir("/content") else "./EfficientNetB0_best.keras"
mc = callbacks.ModelCheckpoint(ckpt_path, monitor="val_accuracy", save_best_only=True)

print("\n--- Stage 1: frozen EfficientNetB0 base, training classification head ---")
train_gen, val_gen, test_gen = make_generators()
hist1 = model.fit(train_gen, validation_data=val_gen, epochs=EPOCHS_STAGE1,
                   callbacks=[es, rlrop, mc], verbose=1)

print(f"\n--- Stage 2: fine-tuning top {UNFREEZE_LAST_N_LAYERS} layers of EfficientNetB0 ---")
base_model.trainable = True
for layer in base_model.layers[:-UNFREEZE_LAST_N_LAYERS]:
    layer.trainable = False
model.compile(optimizer=optimizers.Adam(learning_rate=1e-5), loss=loss_fn, metrics=["accuracy"])
train_gen, val_gen, test_gen = make_generators()
hist2 = model.fit(train_gen, validation_data=val_gen, epochs=EPOCHS_STAGE2,
                   callbacks=[es, rlrop, mc], verbose=1)

history = {
    "acc": hist1.history["accuracy"] + hist2.history["accuracy"],
    "val_acc": hist1.history["val_accuracy"] + hist2.history["val_accuracy"],
    "loss": hist1.history["loss"] + hist2.history["loss"],
    "val_loss": hist1.history["val_loss"] + hist2.history["val_loss"],
}

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].plot(history["acc"], label="train")
axes[0].plot(history["val_acc"], "--", label="val")
axes[0].axvline(EPOCHS_STAGE1 - 0.5, color="gray", linestyle=":", label="fine-tuning starts")
axes[0].set_title("Accuracy")
axes[0].legend()
axes[1].plot(history["loss"], label="train")
axes[1].plot(history["val_loss"], "--", label="val")
axes[1].axvline(EPOCHS_STAGE1 - 0.5, color="gray", linestyle=":")
axes[1].set_title("Loss")
axes[1].legend()
plt.tight_layout()
plt.show()


# SECTION 5 — EVALUATION


print("SECTION 5 - Evaluation on the held-out test set")


_, _, test_gen = make_generators()
y_true = test_gen.classes
y_prob = model.predict(test_gen, verbose=0)
y_pred = np.argmax(y_prob, axis=1)

acc = accuracy_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred, average="macro", zero_division=0)
prec = precision_score(y_true, y_pred, average="macro", zero_division=0)
rec = recall_score(y_true, y_pred, average="macro", zero_division=0)
try:
    auc = roc_auc_score(tf.keras.utils.to_categorical(y_true, NUM_CLASSES), y_prob,
                         multi_class="ovr", average="macro")
except Exception:
    auc = float("nan")

print(f"Accuracy:  {acc:.4f}")
print(f"Macro F1:  {f1:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"ROC-AUC:   {auc:.4f}")
print("\nFull classification report:")
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES, zero_division=0))

# Sanity check for the exact bug you hit: how many distinct classes did the model
# actually predict? If this is 1, something is still structurally wrong.
n_unique_preds = len(np.unique(y_pred))
print(f"\nDistinct classes predicted on the test set: {n_unique_preds} / {NUM_CLASSES}")
if n_unique_preds <= 2:
    print("*** WARNING: the model is barely varying its predictions. Check the Section  ***")
    print("*** 2.05 output above - the Kaggle download may have failed, leaving you on  ***")
    print("*** placeholder images again.                                                ***")

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, cmap="Greens", cbar=True)
plt.title("Confusion matrix - EfficientNetB0 (test set)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.tight_layout()
plt.show()



# SECTION 6 — GRAD-CAM

print("\n" + "=" * 70)
print("SECTION 6 - Grad-CAM explainability")
print("=" * 70)


def find_base_model_and_head(model):

    base_model = None
    head_layers = []
    for layer in model.layers:
        if isinstance(layer, tf.keras.Model):
            base_model = layer
            continue
        if base_model is not None:
            head_layers.append(layer)
    if base_model is None:
        raise ValueError("Could not find the nested base architecture inside this model")
    return base_model, head_layers


def grad_cam(model, img_array, class_index=None):
    base_model, head_layers = find_base_model_and_head(model)
    conv_feature_model = tf.keras.Model(base_model.input, base_model.output)

    classifier_input = tf.keras.Input(shape=base_model.output.shape[1:])
    x = classifier_input
    for layer in head_layers:
        if isinstance(layer, (tf.keras.layers.Dropout, tf.keras.layers.BatchNormalization)):
            x = layer(x, training=False)
        else:
            x = layer(x)
    classifier_model = tf.keras.Model(classifier_input, x)

    with tf.GradientTape() as tape:
        conv_output = conv_feature_model(img_array)
        tape.watch(conv_output)
        predictions = classifier_model(conv_output)
        if class_index is None:
            class_index = int(tf.argmax(predictions[0]))
        loss = predictions[:, class_index]

    grads = tape.gradient(loss, conv_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    conv_output = conv_output[0]
    heatmap = tf.reduce_sum(tf.multiply(pooled_grads, conv_output), axis=-1)
    heatmap = tf.maximum(heatmap, 0) / (tf.math.reduce_max(heatmap) + 1e-8)
    return heatmap.numpy(), int(class_index)


def overlay_heatmap(img_uint8, heatmap, alpha=0.4):
    heatmap = cv2.resize(heatmap, (img_uint8.shape[1], img_uint8.shape[0]))
    heatmap = np.uint8(255 * heatmap)
    heatmap_color = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
    return np.uint8(img_uint8 * (1 - alpha) + heatmap_color * alpha)


_, _, test_gen_raw = make_generators()
test_gen_raw.reset()
sample_imgs, sample_labels = next(test_gen_raw)  # already EfficientNet-preprocessed

fig, axes = plt.subplots(2, 4, figsize=(18, 8))
for i in range(4):
    img_array = np.expand_dims(sample_imgs[i], axis=0)
    heatmap, pred_idx = grad_cam(model, img_array)

    # For display: undo preprocessing back to a viewable 0-255 uint8 image
    display_img = sample_imgs[i] - sample_imgs[i].min()
    display_img = (display_img / (display_img.max() + 1e-8) * 255).astype(np.uint8)
    overlaid = overlay_heatmap(display_img, heatmap)

    axes[0, i].imshow(display_img)
    axes[0, i].axis("off")
    axes[0, i].set_title(f"True: {CLASS_NAMES[np.argmax(sample_labels[i])]}", fontsize=8)
    axes[1, i].imshow(overlaid)
    axes[1, i].axis("off")
    axes[1, i].set_title(f"Pred: {CLASS_NAMES[pred_idx]}", fontsize=8)
plt.suptitle("Grad-CAM - EfficientNetB0")
plt.tight_layout()
plt.show()



# SECTION 7 — EXPORT FOR DEPLOYMENT

print("SECTION 7 - Exporting the model for the website")


EXPORT_DIR = "/content/deployment_package" if os.path.isdir("/content") else "./deployment_package"
os.makedirs(EXPORT_DIR, exist_ok=True)
model.save(os.path.join(EXPORT_DIR, "plant_disease_model.keras"))
with open(os.path.join(EXPORT_DIR, "class_indices.json"), "w") as f:
    json.dump({str(i): name for i, name in enumerate(CLASS_NAMES)}, f, indent=2)
manifest_out = {
    "architecture": "EfficientNetB0",
    "exported_at": datetime.datetime.now().isoformat(),
    "test_accuracy": acc,
    "test_macro_f1": f1,
    "test_precision": prec,
    "test_recall": rec,
    "test_roc_auc": auc,
    "distinct_classes_predicted": n_unique_preds,
    "num_classes": NUM_CLASSES,
    "image_size": IMG_SIZE,
    "used_real_images": real_found > 0,
    "sample_frac_used": SAMPLE_FRAC,
    "fast_mode": FAST_MODE,
    "unfreeze_last_n_layers": UNFREEZE_LAST_N_LAYERS,
}
with open(os.path.join(EXPORT_DIR, "manifest.json"), "w") as f:
    json.dump(manifest_out, f, indent=2, default=str)
print("Deployment package ready:", os.listdir(EXPORT_DIR))
shutil.make_archive(EXPORT_DIR, "zip", EXPORT_DIR)
print(f"{EXPORT_DIR}.zip created.")


# SECTION 7.1 — EXPORT REAL SAMPLE IMAGES TO TEST THE WEBSITE WITH


print("SECTION 7.1 - Exporting real sample images to test the website with")


SAMPLES_PER_CLASS = 2
SAMPLE_DIR = "/content/sample_test_images" if os.path.isdir("/content") else "./sample_test_images"
os.makedirs(SAMPLE_DIR, exist_ok=True)

n_saved = 0
for cls in CLASS_NAMES:
    cls_test_rows = test_df[test_df["disease_class"] == cls]
    real_rows = [r for r in cls_test_rows.itertuples(index=False)
                 if REAL_IMAGES_BY_CLASS.get(cls)]
    for row in real_rows[:SAMPLES_PER_CLASS]:
        dest = os.path.join(SAMPLE_DIR, f"{cls}__{os.path.basename(row.filepath)}")
        shutil.copy(row.filepath, dest)
        n_saved += 1

if n_saved > 0:
    shutil.make_archive(SAMPLE_DIR, "zip", SAMPLE_DIR)
    print(f"Saved {n_saved} real, held-out leaf photos to {SAMPLE_DIR} and zipped to {SAMPLE_DIR}.zip")
    print("Download that zip and upload individual images to the website's Diagnose tab to test it.")
    try:
        from google.colab import files as colab_files
        colab_files.download(f"{SAMPLE_DIR}.zip")
    except Exception:
        print("(Auto-download only works interactively in Colab - if it didn't start, grab the file")
        print(" from the Colab file browser on the left instead: " + SAMPLE_DIR + ".zip)")
else:
    print("No real sample images were available to export - the Kaggle download in Section 2.05")
    print("must not have succeeded. Fix that first, then re-run from Section 2.05 onward.")



# SECTION 8 — WRITE THE WEBSITE (Flask app.py — matching preprocessing fix)


print("SECTION 8 - Writing app.py (self-contained Flask website)")


APP_PY_SOURCE = r'''"""Plant Disease Detection - single-file Flask website (auto-generated).
Uses EfficientNetB0-correct preprocessing: raw [0,255] pixels, no manual /255
rescale (EfficientNet has its own internal Rescaling+Normalization layers).
"""
import os, json, sqlite3, datetime, base64
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras.applications.efficientnet import preprocess_input as efficientnet_preprocess
from flask import Flask, request, jsonify, render_template_string

app = Flask(__name__)

DEPLOY_DIR = "deployment_package"
MODEL_PATH = os.path.join(DEPLOY_DIR, "plant_disease_model.keras")
CLASSES_PATH = os.path.join(DEPLOY_DIR, "class_indices.json")
MANIFEST_PATH = os.path.join(DEPLOY_DIR, "manifest.json")
HISTORY_DB = "scan_history.db"
IMG_SIZE = (224, 224)

GENERIC_ADVICE = {"summary": "No specific guidance on file for this class.",
    "advice": ["Remove affected leaves.", "Avoid overhead watering.", "Improve airflow.",
               "Confirm diagnosis with a local agronomist."], "severity": "unknown"}

TREATMENTS = {
"Apple___Apple_scab": {"summary": "Fungal disease causing olive-green to black scabby leaf/fruit lesions.",
    "advice": ["Apply protectant fungicide from bud break through early summer.",
               "Rake and destroy fallen leaves in autumn.", "Prune for airflow."], "severity": "moderate"},
"Apple___Black_rot": {"summary": "Fungal disease causing leaf spot, fruit rot and cankers.",
    "advice": ["Prune out cankers/dead wood in dormancy.", "Remove mummified fruit.",
               "Apply fungicide per local guidance."], "severity": "moderate-high"},
"Apple___Cedar_apple_rust": {"summary": "Fungal disease needing a juniper/cedar host; bright orange leaf spots.",
    "advice": ["Remove nearby juniper/cedar hosts.", "Apply preventive fungicide in spring.",
               "Choose rust-resistant cultivars."], "severity": "moderate"},
"Apple___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Blueberry___healthy": {"summary": "No disease detected.", "advice": ["Maintain acidic, well-drained soil."], "severity": "none"},
"Cherry___Powdery_mildew": {"summary": "Fungal disease with white powdery growth on leaves/shoots.",
    "advice": ["Apply sulfur-based fungicide at first sign.", "Prune for airflow; avoid excess nitrogen."], "severity": "moderate"},
"Cherry___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Corn___Cercospora_leaf_spot": {"summary": "Fungal disease, rectangular grey-brown lesions.",
    "advice": ["Rotate crops away from maize for a season.", "Use resistant hybrids.",
               "Apply fungicide if disease pressure is high."], "severity": "moderate"},
"Corn___Common_rust": {"summary": "Fungal disease with reddish-brown pustules.",
    "advice": ["Plant resistant hybrids.", "Fungicide rarely needed unless severe/early."], "severity": "low-moderate"},
"Corn___Northern_Leaf_Blight": {"summary": "Fungal disease, cigar-shaped grey-green lesions.",
    "advice": ["Rotate crops and till residue.", "Use resistant hybrids; fungicide if detected early."], "severity": "moderate"},
"Corn___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Grape___Black_rot": {"summary": "Fungal disease, brown leaf spots and mummified berries.",
    "advice": ["Remove mummified berries/infected canes.", "Apply fungicide bud break through veraison."], "severity": "moderate-high"},
"Grape___Esca_(Black_Measles)": {"summary": "Trunk disease causing striped leaf discolouration.",
    "advice": ["Prune out affected wood; disinfect tools.", "Avoid pruning in wet weather."], "severity": "high"},
"Grape___Leaf_blight": {"summary": "Fungal disease causing angular brown leaf spots.",
    "advice": ["Apply protectant fungicide in humid periods.", "Improve canopy airflow."], "severity": "moderate"},
"Grape___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Orange___Haunglongbing": {"summary": "Bacterial citrus greening spread by psyllids; no cure exists.",
    "advice": ["Remove/destroy infected trees promptly.", "Control psyllid populations.",
               "Use certified disease-free stock."], "severity": "severe"},
"Peach___Bacterial_spot": {"summary": "Bacterial disease, dark water-soaked leaf/fruit spots.",
    "advice": ["Plant resistant varieties.", "Apply copper-based bactericide before infection periods."], "severity": "moderate"},
"Peach___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Pepper___Bacterial_spot": {"summary": "Bacterial disease, water-soaked leaf/fruit spots.",
    "advice": ["Use certified disease-free seed.", "Avoid overhead irrigation; copper bactericide."], "severity": "moderate"},
"Pepper___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Potato___Early_blight": {"summary": "Fungal disease, concentric-ring brown leaf spots.",
    "advice": ["Rotate crops.", "Apply fungicide in warm, humid conditions."], "severity": "moderate"},
"Potato___Late_blight": {"summary": "Fast-spreading oomycete disease; devastating in cool, wet weather.",
    "advice": ["Apply protectant fungicide proactively.", "Destroy infected plants/tubers immediately.",
               "Treat as high priority."], "severity": "severe"},
"Potato___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Raspberry___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Soybean___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Squash___Powdery_mildew": {"summary": "Fungal disease, white powdery leaf patches.",
    "advice": ["Apply sulfur/potassium-bicarbonate fungicide.", "Increase spacing; avoid excess nitrogen."], "severity": "moderate"},
"Strawberry___Leaf_scorch": {"summary": "Fungal disease, purple-red blotches merging into scorch.",
    "advice": ["Remove infected leaves after harvest.", "Apply fungicide in wet seasons."], "severity": "moderate"},
"Strawberry___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
"Tomato___Bacterial_spot": {"summary": "Bacterial disease, small dark water-soaked spots.",
    "advice": ["Use certified disease-free seed.", "Apply copper-based bactericide preventively."], "severity": "moderate"},
"Tomato___Early_blight": {"summary": "Fungal disease, concentric-ring lesions on older leaves first.",
    "advice": ["Remove lower infected leaves; mulch.", "Rotate crops; fungicide under high pressure."], "severity": "moderate"},
"Tomato___Late_blight": {"summary": "Fast-spreading oomycete disease; can destroy a crop within days.",
    "advice": ["Apply protectant fungicide ahead of wet/cool forecasts.",
               "Remove and destroy infected plants immediately."], "severity": "severe"},
"Tomato___Leaf_Mold": {"summary": "Fungal disease favoured by high humidity.",
    "advice": ["Improve ventilation; reduce humidity.", "Apply fungicide; remove affected foliage."], "severity": "moderate"},
"Tomato___Septoria_leaf_spot": {"summary": "Fungal disease, small dark-bordered grey-centred spots.",
    "advice": ["Remove infected lower leaves; avoid overhead watering.", "Apply fungicide; rotate crops."], "severity": "moderate"},
"Tomato___Spider_mites": {"summary": "Pest infestation causing stippled, bronzed leaves and webbing.",
    "advice": ["Increase humidity/hose foliage.", "Apply miticide or insecticidal soap."], "severity": "moderate"},
"Tomato___Target_Spot": {"summary": "Fungal disease, concentric target-like lesions.",
    "advice": ["Improve airflow; avoid leaf wetness.", "Apply fungicide under high pressure."], "severity": "moderate"},
"Tomato___Tomato_Yellow_Leaf_Curl_Virus": {"summary": "Viral disease spread by whiteflies; no cure once infected.",
    "advice": ["Control whitefly vectors.", "Remove infected plants; use resistant varieties."], "severity": "severe"},
"Tomato___Tomato_mosaic_virus": {"summary": "Viral disease causing mottled mosaic leaf patterns.",
    "advice": ["Remove infected plants; disinfect tools.", "Use certified virus-free seed."], "severity": "moderate-high"},
"Tomato___healthy": {"summary": "No disease detected.", "advice": ["Continue routine monitoring."], "severity": "none"},
}

def get_treatment(class_name):
    return TREATMENTS.get(class_name, GENERIC_ADVICE)

def build_detectable_summary():
    crops = {}
    for class_name in TREATMENTS:
        crop, _, condition = class_name.partition("___")
        crop = crop.replace("_", " ")
        condition = condition.replace("_", " ").strip()
        entry = crops.setdefault(crop, {"diseases": [], "healthy": False})
        if condition.lower() == "healthy":
            entry["healthy"] = True
        else:
            entry["diseases"].append(condition)
    for entry in crops.values():
        entry["diseases"].sort()
    return dict(sorted(crops.items()))

_model = None
_idx_to_class = None
_manifest = None

def load_resources():
    global _model, _idx_to_class, _manifest
    if _model is None and os.path.exists(MODEL_PATH):
        _model = tf.keras.models.load_model(MODEL_PATH)
        with open(CLASSES_PATH) as f:
            _idx_to_class = json.load(f)
        if os.path.exists(MANIFEST_PATH):
            with open(MANIFEST_PATH) as f:
                _manifest = json.load(f)
    return _model, _idx_to_class, _manifest

def init_db():
    conn = sqlite3.connect(HISTORY_DB, check_same_thread=False)
    conn.execute("CREATE TABLE IF NOT EXISTS scans (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp TEXT, predicted_class TEXT, confidence REAL)")
    conn.commit()
    return conn

def log_scan(conn, predicted_class, confidence):
    conn.execute("INSERT INTO scans (timestamp, predicted_class, confidence) VALUES (?, ?, ?)",
                 (datetime.datetime.now().isoformat(), predicted_class, float(confidence)))
    conn.commit()

def fetch_history(conn):
    return conn.execute("SELECT timestamp, predicted_class, confidence FROM scans ORDER BY id DESC LIMIT 50").fetchall()

def find_base_model_and_head(model):
    base_model = None
    head_layers = []
    for layer in model.layers:
        if isinstance(layer, tf.keras.Model):
            base_model = layer
            continue
        if base_model is not None:
            head_layers.append(layer)
    if base_model is None:
        raise ValueError("Could not find the nested base architecture inside this model")
    return base_model, head_layers

def grad_cam(model, img_array, class_index=None):
    base_model, head_layers = find_base_model_and_head(model)
    conv_feature_model = tf.keras.Model(base_model.input, base_model.output)
    classifier_input = tf.keras.Input(shape=base_model.output.shape[1:])
    x = classifier_input
    for layer in head_layers:
        if isinstance(layer, (tf.keras.layers.Dropout, tf.keras.layers.BatchNormalization)):
            x = layer(x, training=False)
        else:
            x = layer(x)
    classifier_model = tf.keras.Model(classifier_input, x)
    with tf.GradientTape() as tape:
        conv_output = conv_feature_model(img_array)
        tape.watch(conv_output)
        predictions = classifier_model(conv_output)
        if class_index is None:
            class_index = tf.argmax(predictions[0])
        loss = predictions[:, class_index]
    grads = tape.gradient(loss, conv_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    conv_output = conv_output[0]
    heatmap = tf.reduce_sum(tf.multiply(pooled_grads, conv_output), axis=-1)
    heatmap = tf.maximum(heatmap, 0) / (tf.math.reduce_max(heatmap) + 1e-8)
    return heatmap.numpy(), int(class_index)

def overlay_heatmap(img_rgb_uint8, heatmap, alpha=0.4):
    heatmap = cv2.resize(heatmap, (img_rgb_uint8.shape[1], img_rgb_uint8.shape[0]))
    heatmap = np.uint8(255 * heatmap)
    heatmap_color = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
    return np.uint8(img_rgb_uint8 * (1 - alpha) + heatmap_color * alpha)

def decode_image(file_storage):
    data = np.frombuffer(file_storage.read(), np.uint8)
    img_bgr = cv2.imdecode(data, cv2.IMREAD_COLOR)
    return cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

def prep_for_model(img_rgb_uint8):
    """Returns (model_input, display_image). model_input keeps raw [0,255] pixels
    (EfficientNet-correct) run through efficientnet_preprocess (a documented
    no-op); display_image stays plain uint8 [0,255] for showing in the browser."""
    resized = cv2.resize(img_rgb_uint8, IMG_SIZE)
    model_input = efficientnet_preprocess(resized.astype(np.float32))
    return np.expand_dims(model_input, axis=0), resized

def encode_png_b64(img_rgb_uint8):
    img_bgr = cv2.cvtColor(img_rgb_uint8, cv2.COLOR_RGB2BGR)
    ok, buf = cv2.imencode(".png", img_bgr)
    return base64.b64encode(buf.tobytes()).decode("utf-8")


INDEX_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Plant Disease Detection</title>
<style>
  :root {
    --green-dark:#1B4332; --green-mid:#2D6A4F; --green-light:#D8F3DC;
    --sev-none:#D8F3DC; --sev-low:#FFF3CD; --sev-mod:#FFE5B4; --sev-severe:#F8D7DA;
  }
  * { box-sizing: border-box; }
  body { margin:0; font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif;
         background:#F7FAF8; color:#1B1B1B; font-size:18px; }
  header { background:var(--green-dark); color:#fff; padding:18px 28px; display:flex;
           align-items:center; justify-content:space-between; flex-wrap:wrap; }
  header h1 { margin:0; font-size:1.4rem; }
  nav { display:flex; gap:8px; }
  nav button { background:transparent; border:2px solid #fff; color:#fff; padding:8px 16px;
               border-radius:8px; font-size:1rem; cursor:pointer; }
  nav button.active, nav button:hover { background:#fff; color:var(--green-dark); }
  main { max-width: 1000px; margin: 0 auto; padding: 24px; }
  .card { background:#fff; border-radius:12px; padding:22px; margin-bottom:20px;
          box-shadow:0 1px 4px rgba(0,0,0,0.08); }
  .dropzone { border:3px dashed var(--green-mid); border-radius:12px; padding:40px;
              text-align:center; cursor:pointer; color:var(--green-dark); }
  .dropzone.dragover { background:var(--green-light); }
  .btn { background:var(--green-mid); color:#fff; border:none; padding:12px 22px;
         border-radius:8px; font-size:1.05rem; cursor:pointer; margin-top:14px; }
  .btn:hover { background:var(--green-dark); }
  .btn:disabled { opacity:0.5; cursor:not-allowed; }
  .results { display:grid; grid-template-columns: 1fr 1fr; gap:20px; margin-top:20px; }
  .results img { width:100%; border-radius:10px; }
  @media (max-width:700px){ .results{ grid-template-columns: 1fr; } }
  .severity-none { background:var(--sev-none); }
  .severity-low, .severity-low-moderate { background:var(--sev-low); }
  .severity-moderate, .severity-moderate-high, .severity-unknown { background:var(--sev-mod); }
  .severity-severe, .severity-high { background:var(--sev-severe); }
  .sev-box { padding:14px; border-radius:8px; margin-top:12px; }
  table { width:100%; border-collapse: collapse; }
  th, td { text-align:left; padding:8px 10px; border-bottom:1px solid #eee; }
  .confidence { font-size:1.6rem; font-weight:700; color:var(--green-dark); }
  .hidden { display:none; }
  .muted { color:#666; font-size:0.95rem; }
  .bar-row { display:flex; align-items:center; gap:8px; margin:6px 0; }
  .bar-track { flex:1; background:#eee; border-radius:6px; height:14px; overflow:hidden; }
  .bar-fill { background:var(--green-mid); height:100%; }
  #spinner { display:none; }
</style>
</head>
<body>
<header>
  <h1>Plant Disease Detection</h1>
  <nav>
    <button class="tab-btn active" data-tab="diagnose">Diagnose</button>
    <button class="tab-btn" data-tab="history">History</button>
    <button class="tab-btn" data-tab="about">About</button>
  </nav>
</header>
<main>

  <section id="tab-diagnose">
    <div class="card">
      <p>Upload a clear photo of a single leaf for an instant diagnosis, a visual explanation, and next steps.</p>
      <div class="dropzone" id="dropzone">
        <p id="dz-text">Drag &amp; drop a leaf photo here, or click to choose a file</p>
        <input type="file" id="fileInput" accept="image/*" class="hidden">
      </div>
      <button class="btn" id="analyzeBtn" disabled>Analyse photo</button>
      <span id="spinner" class="muted">Analysing...</span>
    </div>

    <div class="results hidden" id="resultsBlock">
      <div class="card">
        <h3>Your photo</h3>
        <img id="origImg" alt="Uploaded leaf photo">
      </div>
      <div class="card">
        <h3>Evidence Gathered by the Model</h3>
        <img id="heatImg" alt="Grad-CAM heatmap overlay">
        <p class="muted">Red/yellow regions influenced the prediction most</p>
      </div>
    </div>

    <div class="card hidden" id="verdictCard">
      <h2 id="predictedClass"></h2>
      <div class="confidence" id="confidenceVal"></div>
      <div id="lowConfWarning" class="muted hidden">Confidence is low - try a clearer photo, or confirm with an agronomist.</div>
      <div class="sev-box" id="sevBox">
        <b>Summary:</b> <span id="sevSummary"></span><br>
        <b>Severity:</b> <span id="sevLevel"></span>
      </div>
      <p><b>Recommended next steps:</b></p>
      <ul id="adviceList"></ul>
      <p class="muted">This tool supports, but does not replace, professional agronomic advice.</p>
    </div>
  </section>

  <section id="tab-history" class="hidden">
    <div class="card">
      <h2>Scan History &amp; Analytics</h2>
      <div id="historyEmpty" class="muted">No scans recorded yet.</div>
      <div id="historyChart"></div>
      <table id="historyTable" class="hidden">
        <thead><tr><th>Timestamp</th><th>Predicted class</th><th>Confidence</th></tr></thead>
        <tbody id="historyBody"></tbody>
      </table>
    </div>
  </section>

  <section id="tab-about" class="hidden">
    <div class="card">
      <h2>About This Tool</h2>
      <p>Deployment website for the Automated Plant Disease Detection project (EfficientNetB0).
         Kept separate from the training pipeline by design.</p>
      <h3>Plants &amp; diseases this model can detect</h3>
      <div id="detectableBox" class="muted">Loading...</div>
      <h3>Current deployed model</h3>
      <pre id="manifestBox">Loading...</pre>
      <h3>Accessibility &amp; design notes</h3>
      <ul>
        <li>Large fonts, high contrast, colour-coded severity.</li>
        <li>Plain-language disease names.</li>
        <li>Personas: smallholder farmer, extension officer.</li>
      </ul>
    </div>
  </section>

</main>

<script>
const tabs = document.querySelectorAll(".tab-btn");
const sections = { diagnose: document.getElementById("tab-diagnose"),
                    history: document.getElementById("tab-history"),
                    about: document.getElementById("tab-about") };
tabs.forEach(btn => btn.addEventListener("click", () => {
  tabs.forEach(b => b.classList.remove("active"));
  btn.classList.add("active");
  Object.values(sections).forEach(s => s.classList.add("hidden"));
  sections[btn.dataset.tab].classList.remove("hidden");
  if (btn.dataset.tab === "history") loadHistory();
  if (btn.dataset.tab === "about") loadAbout();
}));

const dropzone = document.getElementById("dropzone");
const fileInput = document.getElementById("fileInput");
const analyzeBtn = document.getElementById("analyzeBtn");
let selectedFile = null;

dropzone.addEventListener("click", () => fileInput.click());
dropzone.addEventListener("dragover", e => { e.preventDefault(); dropzone.classList.add("dragover"); });
dropzone.addEventListener("dragleave", () => dropzone.classList.remove("dragover"));
dropzone.addEventListener("drop", e => {
  e.preventDefault(); dropzone.classList.remove("dragover");
  if (e.dataTransfer.files.length) setFile(e.dataTransfer.files[0]);
});
fileInput.addEventListener("change", () => { if (fileInput.files.length) setFile(fileInput.files[0]); });

function setFile(f) {
  selectedFile = f;
  document.getElementById("dz-text").textContent = "Selected: " + f.name;
  analyzeBtn.disabled = false;
}

analyzeBtn.addEventListener("click", async () => {
  if (!selectedFile) return;
  analyzeBtn.disabled = true;
  document.getElementById("spinner").style.display = "inline";
  const fd = new FormData();
  fd.append("image", selectedFile);
  try {
    const res = await fetch("/api/predict", { method: "POST", body: fd });
    const data = await res.json();
    if (data.error) { alert(data.error); return; }
    document.getElementById("resultsBlock").classList.remove("hidden");
    document.getElementById("verdictCard").classList.remove("hidden");
    document.getElementById("origImg").src = "data:image/png;base64," + data.original_image;
    document.getElementById("heatImg").src = "data:image/png;base64," + data.heatmap_image;
    document.getElementById("predictedClass").textContent = "Result: " + data.predicted_class;
    document.getElementById("confidenceVal").textContent = "Confidence: " + data.confidence + "%";
    const lowWarn = document.getElementById("lowConfWarning");
    lowWarn.classList.toggle("hidden", data.confidence >= 60);
    const sevBox = document.getElementById("sevBox");
    sevBox.className = "sev-box severity-" + data.treatment.severity.replace(/ /g, "-");
    document.getElementById("sevSummary").textContent = data.treatment.summary;
    document.getElementById("sevLevel").textContent = data.treatment.severity;
    const list = document.getElementById("adviceList");
    list.innerHTML = "";
    data.treatment.advice.forEach(step => {
      const li = document.createElement("li"); li.textContent = step; list.appendChild(li);
    });
  } catch (err) {
    alert("Something went wrong contacting the server: " + err);
  } finally {
    analyzeBtn.disabled = false;
    document.getElementById("spinner").style.display = "none";
  }
});

async function loadHistory() {
  const res = await fetch("/api/history");
  const rows = await res.json();
  const empty = document.getElementById("historyEmpty");
  const table = document.getElementById("historyTable");
  const body = document.getElementById("historyBody");
  const chart = document.getElementById("historyChart");
  if (!rows.length) { empty.classList.remove("hidden"); table.classList.add("hidden"); chart.innerHTML=""; return; }
  empty.classList.add("hidden"); table.classList.remove("hidden");
  body.innerHTML = "";
  const counts = {};
  rows.forEach(r => {
    const tr = document.createElement("tr");
    tr.innerHTML = `<td>${r.timestamp}</td><td>${r.predicted_class}</td><td>${r.confidence}%</td>`;
    body.appendChild(tr);
    counts[r.predicted_class] = (counts[r.predicted_class] || 0) + 1;
  });
  const maxCount = Math.max(...Object.values(counts));
  chart.innerHTML = "<h3>Most frequently detected issues</h3>";
  Object.entries(counts).sort((a,b)=>b[1]-a[1]).forEach(([cls, count]) => {
    const pct = (count / maxCount) * 100;
    chart.innerHTML += `<div class="bar-row"><div style="width:220px">${cls}</div>
      <div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div>
      <div style="width:30px">${count}</div></div>`;
  });
}

async function loadAbout() {
  const res = await fetch("/api/about");
  const data = await res.json();
  document.getElementById("manifestBox").textContent = JSON.stringify(data.model, null, 2);

  const detectable = data.detectable || {};
  const box = document.getElementById("detectableBox");
  box.innerHTML = "";
  const cropNames = Object.keys(detectable).sort();
  if (cropNames.length === 0) {
    box.textContent = "No classes on file yet.";
    return;
  }
  const list = document.createElement("ul");
  cropNames.forEach(crop => {
    const info = detectable[crop];
    const diseases = info.diseases || [];
    const parts = [];
    if (diseases.length) parts.push(diseases.join(", "));
    if (info.healthy) parts.push("healthy");
    const li = document.createElement("li");
    li.innerHTML = "<strong>" + crop + "</strong>: " + (parts.join(", ") || "no classes on file");
    list.appendChild(li);
  });
  box.appendChild(list);
}
</script>
</body>
</html>
"""


@app.route("/")
def index():
    return render_template_string(INDEX_HTML)


@app.route("/api/predict", methods=["POST"])
def predict():
    model, idx_to_class, manifest = load_resources()
    if model is None:
        return jsonify({"error": "No trained model found. Run the pipeline's export step first so deployment_package/ sits next to this app."}), 400
    file = request.files.get("image")
    if not file:
        return jsonify({"error": "No image uploaded"}), 400
    img_rgb = decode_image(file)
    img_array, display_img = prep_for_model(img_rgb)
    preds = model.predict(img_array, verbose=0)[0]
    pred_idx = int(np.argmax(preds))
    confidence = float(preds[pred_idx])
    predicted_class = idx_to_class.get(str(pred_idx), f"class_{pred_idx}")
    heatmap, _ = grad_cam(model, img_array, class_index=pred_idx)
    overlay = overlay_heatmap(display_img, heatmap)

    treatment = get_treatment(predicted_class)
    conn = init_db()
    log_scan(conn, predicted_class, confidence)

    return jsonify({
        "predicted_class": predicted_class.replace("___", " - ").replace("_", " "),
        "confidence": round(confidence * 100, 1),
        "treatment": treatment,
        "original_image": encode_png_b64(display_img),
        "heatmap_image": encode_png_b64(overlay),
    })


@app.route("/api/history")
def history():
    conn = init_db()
    rows = fetch_history(conn)
    return jsonify([
        {"timestamp": r[0], "predicted_class": r[1].replace("___", " - ").replace("_", " "),
         "confidence": round(r[2] * 100, 1)}
        for r in rows
    ])

@app.route("/api/about")
def about():
    _, _, manifest = load_resources()
    return jsonify({
        "model": manifest or {"status": "no model exported yet"},
        "detectable": build_detectable_summary(),
    })


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False, threaded=True)
'''

with open("app.py", "w") as f:
    f.write(APP_PY_SOURCE)
print("app.py written to disk (" + str(len(APP_PY_SOURCE)) + " characters).")



# SECTION 9 — LAUNCH THE WEBSITE


print("SECTION 9 - Launching the website")



NGROK_AUTH_TOKEN = ""

subprocess.Popen([sys.executable, "app.py"])
time.sleep(4)

try:
    from google.colab.output import eval_js
    proxied_url = eval_js("google.colab.kernel.proxyPort(5000)")
    print("\n>>> CLICK THIS LINK TO OPEN YOUR WEBSITE:", proxied_url, "<<<\n")
except ImportError:
    print("\nNot running in Colab - open http://localhost:5000 directly in your browser.\n")

if NGROK_AUTH_TOKEN:
    from pyngrok import ngrok
    ngrok.set_auth_token(NGROK_AUTH_TOKEN)
    public_url = ngrok.connect(5000)
    print("Public ngrok URL (shareable outside Colab):", public_url)

print("\nTo run this same website later, outside Colab:")
print("  pip install flask tensorflow opencv-python-headless")
print("  python app.py")
print("  then open http://localhost:5000 in your browser")



# SECTION 10 — USABILITY EVALUATION (SUS)


print("/nSECTION 10 - System Usability Scale (SUS) scorer/n")



def compute_sus_score(responses):
    assert len(responses) == 10, "SUS requires exactly 10 responses"
    total = 0
    for i, r in enumerate(responses):
        pos = (i % 2 == 0)
        total += (r - 1) if pos else (5 - r)
    return total * 2.5


example_responses = [4, 2, 5, 2, 4, 1, 5, 2, 4, 2]
print("Example SUS score:", compute_sus_score(example_responses), "/ 100 (illustrative only - replace with real participant data)")

print("\n" + "=" * 70)
print("PIPELINE COMPLETE")
print("=" * 70)
print("EfficientNetB0 training, evaluation, Grad-CAM, export, and the live website have all run,")
print("trained on real downloaded PlantVillage photos (see Section 2.05 above for how many).")
print("For the highest accuracy: set FAST_MODE=False and SAMPLE_FRAC=1.0, then re-run.")